(cl:in-package kinova_msgs-srv)
(cl:export '(INERTIA_LINEAR-VAL
          INERTIA_LINEAR
          INERTIA_ANGULAR-VAL
          INERTIA_ANGULAR
          DAMPING_LINEAR-VAL
          DAMPING_LINEAR
          DAMPING_ANGULAR-VAL
          DAMPING_ANGULAR
          FORCE_MIN_LINEAR-VAL
          FORCE_MIN_LINEAR
          FORCE_MIN_ANGULAR-VAL
          FORCE_MIN_ANGULAR
          FORCE_MAX_LINEAR-VAL
          FORCE_MAX_LINEAR
          FORCE_MAX_ANGULAR-VAL
          FORCE_MAX_ANGULAR
))