// Generated by gencpp from file kinova_msgs/AddPoseToCartesianTrajectory.msg
// DO NOT EDIT!


#ifndef KINOVA_MSGS_MESSAGE_ADDPOSETOCARTESIANTRAJECTORY_H
#define KINOVA_MSGS_MESSAGE_ADDPOSETOCARTESIANTRAJECTORY_H

#include <ros/service_traits.h>


#include <kinova_msgs/AddPoseToCartesianTrajectoryRequest.h>
#include <kinova_msgs/AddPoseToCartesianTrajectoryResponse.h>


namespace kinova_msgs
{

struct AddPoseToCartesianTrajectory
{

typedef AddPoseToCartesianTrajectoryRequest Request;
typedef AddPoseToCartesianTrajectoryResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddPoseToCartesianTrajectory
} // namespace kinova_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::kinova_msgs::AddPoseToCartesianTrajectory > {
  static const char* value()
  {
    return "e831d993faea563f6fe69d7db9b384c9";
  }

  static const char* value(const ::kinova_msgs::AddPoseToCartesianTrajectory&) { return value(); }
};

template<>
struct DataType< ::kinova_msgs::AddPoseToCartesianTrajectory > {
  static const char* value()
  {
    return "kinova_msgs/AddPoseToCartesianTrajectory";
  }

  static const char* value(const ::kinova_msgs::AddPoseToCartesianTrajectory&) { return value(); }
};


// service_traits::MD5Sum< ::kinova_msgs::AddPoseToCartesianTrajectoryRequest> should match 
// service_traits::MD5Sum< ::kinova_msgs::AddPoseToCartesianTrajectory > 
template<>
struct MD5Sum< ::kinova_msgs::AddPoseToCartesianTrajectoryRequest>
{
  static const char* value()
  {
    return MD5Sum< ::kinova_msgs::AddPoseToCartesianTrajectory >::value();
  }
  static const char* value(const ::kinova_msgs::AddPoseToCartesianTrajectoryRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::kinova_msgs::AddPoseToCartesianTrajectoryRequest> should match 
// service_traits::DataType< ::kinova_msgs::AddPoseToCartesianTrajectory > 
template<>
struct DataType< ::kinova_msgs::AddPoseToCartesianTrajectoryRequest>
{
  static const char* value()
  {
    return DataType< ::kinova_msgs::AddPoseToCartesianTrajectory >::value();
  }
  static const char* value(const ::kinova_msgs::AddPoseToCartesianTrajectoryRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::kinova_msgs::AddPoseToCartesianTrajectoryResponse> should match 
// service_traits::MD5Sum< ::kinova_msgs::AddPoseToCartesianTrajectory > 
template<>
struct MD5Sum< ::kinova_msgs::AddPoseToCartesianTrajectoryResponse>
{
  static const char* value()
  {
    return MD5Sum< ::kinova_msgs::AddPoseToCartesianTrajectory >::value();
  }
  static const char* value(const ::kinova_msgs::AddPoseToCartesianTrajectoryResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::kinova_msgs::AddPoseToCartesianTrajectoryResponse> should match 
// service_traits::DataType< ::kinova_msgs::AddPoseToCartesianTrajectory > 
template<>
struct DataType< ::kinova_msgs::AddPoseToCartesianTrajectoryResponse>
{
  static const char* value()
  {
    return DataType< ::kinova_msgs::AddPoseToCartesianTrajectory >::value();
  }
  static const char* value(const ::kinova_msgs::AddPoseToCartesianTrajectoryResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KINOVA_MSGS_MESSAGE_ADDPOSETOCARTESIANTRAJECTORY_H
