// Generated by gencpp from file kinova_msgs/ClearTrajectories.msg
// DO NOT EDIT!


#ifndef KINOVA_MSGS_MESSAGE_CLEARTRAJECTORIES_H
#define KINOVA_MSGS_MESSAGE_CLEARTRAJECTORIES_H

#include <ros/service_traits.h>


#include <kinova_msgs/ClearTrajectoriesRequest.h>
#include <kinova_msgs/ClearTrajectoriesResponse.h>


namespace kinova_msgs
{

struct ClearTrajectories
{

typedef ClearTrajectoriesRequest Request;
typedef ClearTrajectoriesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ClearTrajectories
} // namespace kinova_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::kinova_msgs::ClearTrajectories > {
  static const char* value()
  {
    return "c22f2a1ed8654a0b365f1bb3f7ff2c0f";
  }

  static const char* value(const ::kinova_msgs::ClearTrajectories&) { return value(); }
};

template<>
struct DataType< ::kinova_msgs::ClearTrajectories > {
  static const char* value()
  {
    return "kinova_msgs/ClearTrajectories";
  }

  static const char* value(const ::kinova_msgs::ClearTrajectories&) { return value(); }
};


// service_traits::MD5Sum< ::kinova_msgs::ClearTrajectoriesRequest> should match 
// service_traits::MD5Sum< ::kinova_msgs::ClearTrajectories > 
template<>
struct MD5Sum< ::kinova_msgs::ClearTrajectoriesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::kinova_msgs::ClearTrajectories >::value();
  }
  static const char* value(const ::kinova_msgs::ClearTrajectoriesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::kinova_msgs::ClearTrajectoriesRequest> should match 
// service_traits::DataType< ::kinova_msgs::ClearTrajectories > 
template<>
struct DataType< ::kinova_msgs::ClearTrajectoriesRequest>
{
  static const char* value()
  {
    return DataType< ::kinova_msgs::ClearTrajectories >::value();
  }
  static const char* value(const ::kinova_msgs::ClearTrajectoriesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::kinova_msgs::ClearTrajectoriesResponse> should match 
// service_traits::MD5Sum< ::kinova_msgs::ClearTrajectories > 
template<>
struct MD5Sum< ::kinova_msgs::ClearTrajectoriesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::kinova_msgs::ClearTrajectories >::value();
  }
  static const char* value(const ::kinova_msgs::ClearTrajectoriesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::kinova_msgs::ClearTrajectoriesResponse> should match 
// service_traits::DataType< ::kinova_msgs::ClearTrajectories > 
template<>
struct DataType< ::kinova_msgs::ClearTrajectoriesResponse>
{
  static const char* value()
  {
    return DataType< ::kinova_msgs::ClearTrajectories >::value();
  }
  static const char* value(const ::kinova_msgs::ClearTrajectoriesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KINOVA_MSGS_MESSAGE_CLEARTRAJECTORIES_H
