// Generated by gencpp from file kinova_msgs/HomeArm.msg
// DO NOT EDIT!


#ifndef KINOVA_MSGS_MESSAGE_HOMEARM_H
#define KINOVA_MSGS_MESSAGE_HOMEARM_H

#include <ros/service_traits.h>


#include <kinova_msgs/HomeArmRequest.h>
#include <kinova_msgs/HomeArmResponse.h>


namespace kinova_msgs
{

struct HomeArm
{

typedef HomeArmRequest Request;
typedef HomeArmResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct HomeArm
} // namespace kinova_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::kinova_msgs::HomeArm > {
  static const char* value()
  {
    return "46e470f2c1a7177398c57a43eafe8d67";
  }

  static const char* value(const ::kinova_msgs::HomeArm&) { return value(); }
};

template<>
struct DataType< ::kinova_msgs::HomeArm > {
  static const char* value()
  {
    return "kinova_msgs/HomeArm";
  }

  static const char* value(const ::kinova_msgs::HomeArm&) { return value(); }
};


// service_traits::MD5Sum< ::kinova_msgs::HomeArmRequest> should match 
// service_traits::MD5Sum< ::kinova_msgs::HomeArm > 
template<>
struct MD5Sum< ::kinova_msgs::HomeArmRequest>
{
  static const char* value()
  {
    return MD5Sum< ::kinova_msgs::HomeArm >::value();
  }
  static const char* value(const ::kinova_msgs::HomeArmRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::kinova_msgs::HomeArmRequest> should match 
// service_traits::DataType< ::kinova_msgs::HomeArm > 
template<>
struct DataType< ::kinova_msgs::HomeArmRequest>
{
  static const char* value()
  {
    return DataType< ::kinova_msgs::HomeArm >::value();
  }
  static const char* value(const ::kinova_msgs::HomeArmRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::kinova_msgs::HomeArmResponse> should match 
// service_traits::MD5Sum< ::kinova_msgs::HomeArm > 
template<>
struct MD5Sum< ::kinova_msgs::HomeArmResponse>
{
  static const char* value()
  {
    return MD5Sum< ::kinova_msgs::HomeArm >::value();
  }
  static const char* value(const ::kinova_msgs::HomeArmResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::kinova_msgs::HomeArmResponse> should match 
// service_traits::DataType< ::kinova_msgs::HomeArm > 
template<>
struct DataType< ::kinova_msgs::HomeArmResponse>
{
  static const char* value()
  {
    return DataType< ::kinova_msgs::HomeArm >::value();
  }
  static const char* value(const ::kinova_msgs::HomeArmResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KINOVA_MSGS_MESSAGE_HOMEARM_H
