// Generated by gencpp from file kinova_msgs/RunCOMParametersEstimation.msg
// DO NOT EDIT!


#ifndef KINOVA_MSGS_MESSAGE_RUNCOMPARAMETERSESTIMATION_H
#define KINOVA_MSGS_MESSAGE_RUNCOMPARAMETERSESTIMATION_H

#include <ros/service_traits.h>


#include <kinova_msgs/RunCOMParametersEstimationRequest.h>
#include <kinova_msgs/RunCOMParametersEstimationResponse.h>


namespace kinova_msgs
{

struct RunCOMParametersEstimation
{

typedef RunCOMParametersEstimationRequest Request;
typedef RunCOMParametersEstimationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RunCOMParametersEstimation
} // namespace kinova_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::kinova_msgs::RunCOMParametersEstimation > {
  static const char* value()
  {
    return "c22f2a1ed8654a0b365f1bb3f7ff2c0f";
  }

  static const char* value(const ::kinova_msgs::RunCOMParametersEstimation&) { return value(); }
};

template<>
struct DataType< ::kinova_msgs::RunCOMParametersEstimation > {
  static const char* value()
  {
    return "kinova_msgs/RunCOMParametersEstimation";
  }

  static const char* value(const ::kinova_msgs::RunCOMParametersEstimation&) { return value(); }
};


// service_traits::MD5Sum< ::kinova_msgs::RunCOMParametersEstimationRequest> should match 
// service_traits::MD5Sum< ::kinova_msgs::RunCOMParametersEstimation > 
template<>
struct MD5Sum< ::kinova_msgs::RunCOMParametersEstimationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::kinova_msgs::RunCOMParametersEstimation >::value();
  }
  static const char* value(const ::kinova_msgs::RunCOMParametersEstimationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::kinova_msgs::RunCOMParametersEstimationRequest> should match 
// service_traits::DataType< ::kinova_msgs::RunCOMParametersEstimation > 
template<>
struct DataType< ::kinova_msgs::RunCOMParametersEstimationRequest>
{
  static const char* value()
  {
    return DataType< ::kinova_msgs::RunCOMParametersEstimation >::value();
  }
  static const char* value(const ::kinova_msgs::RunCOMParametersEstimationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::kinova_msgs::RunCOMParametersEstimationResponse> should match 
// service_traits::MD5Sum< ::kinova_msgs::RunCOMParametersEstimation > 
template<>
struct MD5Sum< ::kinova_msgs::RunCOMParametersEstimationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::kinova_msgs::RunCOMParametersEstimation >::value();
  }
  static const char* value(const ::kinova_msgs::RunCOMParametersEstimationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::kinova_msgs::RunCOMParametersEstimationResponse> should match 
// service_traits::DataType< ::kinova_msgs::RunCOMParametersEstimation > 
template<>
struct DataType< ::kinova_msgs::RunCOMParametersEstimationResponse>
{
  static const char* value()
  {
    return DataType< ::kinova_msgs::RunCOMParametersEstimation >::value();
  }
  static const char* value(const ::kinova_msgs::RunCOMParametersEstimationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KINOVA_MSGS_MESSAGE_RUNCOMPARAMETERSESTIMATION_H
