// Generated by gencpp from file kinova_msgs/SetEndEffectorOffset.msg
// DO NOT EDIT!


#ifndef KINOVA_MSGS_MESSAGE_SETENDEFFECTOROFFSET_H
#define KINOVA_MSGS_MESSAGE_SETENDEFFECTOROFFSET_H

#include <ros/service_traits.h>


#include <kinova_msgs/SetEndEffectorOffsetRequest.h>
#include <kinova_msgs/SetEndEffectorOffsetResponse.h>


namespace kinova_msgs
{

struct SetEndEffectorOffset
{

typedef SetEndEffectorOffsetRequest Request;
typedef SetEndEffectorOffsetResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetEndEffectorOffset
} // namespace kinova_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::kinova_msgs::SetEndEffectorOffset > {
  static const char* value()
  {
    return "7a5c04366489f137e01b31118dcce900";
  }

  static const char* value(const ::kinova_msgs::SetEndEffectorOffset&) { return value(); }
};

template<>
struct DataType< ::kinova_msgs::SetEndEffectorOffset > {
  static const char* value()
  {
    return "kinova_msgs/SetEndEffectorOffset";
  }

  static const char* value(const ::kinova_msgs::SetEndEffectorOffset&) { return value(); }
};


// service_traits::MD5Sum< ::kinova_msgs::SetEndEffectorOffsetRequest> should match 
// service_traits::MD5Sum< ::kinova_msgs::SetEndEffectorOffset > 
template<>
struct MD5Sum< ::kinova_msgs::SetEndEffectorOffsetRequest>
{
  static const char* value()
  {
    return MD5Sum< ::kinova_msgs::SetEndEffectorOffset >::value();
  }
  static const char* value(const ::kinova_msgs::SetEndEffectorOffsetRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::kinova_msgs::SetEndEffectorOffsetRequest> should match 
// service_traits::DataType< ::kinova_msgs::SetEndEffectorOffset > 
template<>
struct DataType< ::kinova_msgs::SetEndEffectorOffsetRequest>
{
  static const char* value()
  {
    return DataType< ::kinova_msgs::SetEndEffectorOffset >::value();
  }
  static const char* value(const ::kinova_msgs::SetEndEffectorOffsetRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::kinova_msgs::SetEndEffectorOffsetResponse> should match 
// service_traits::MD5Sum< ::kinova_msgs::SetEndEffectorOffset > 
template<>
struct MD5Sum< ::kinova_msgs::SetEndEffectorOffsetResponse>
{
  static const char* value()
  {
    return MD5Sum< ::kinova_msgs::SetEndEffectorOffset >::value();
  }
  static const char* value(const ::kinova_msgs::SetEndEffectorOffsetResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::kinova_msgs::SetEndEffectorOffsetResponse> should match 
// service_traits::DataType< ::kinova_msgs::SetEndEffectorOffset > 
template<>
struct DataType< ::kinova_msgs::SetEndEffectorOffsetResponse>
{
  static const char* value()
  {
    return DataType< ::kinova_msgs::SetEndEffectorOffset >::value();
  }
  static const char* value(const ::kinova_msgs::SetEndEffectorOffsetResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KINOVA_MSGS_MESSAGE_SETENDEFFECTOROFFSET_H
