// Generated by gencpp from file kinova_msgs/SetForceControlParams.msg
// DO NOT EDIT!


#ifndef KINOVA_MSGS_MESSAGE_SETFORCECONTROLPARAMS_H
#define KINOVA_MSGS_MESSAGE_SETFORCECONTROLPARAMS_H

#include <ros/service_traits.h>


#include <kinova_msgs/SetForceControlParamsRequest.h>
#include <kinova_msgs/SetForceControlParamsResponse.h>


namespace kinova_msgs
{

struct SetForceControlParams
{

typedef SetForceControlParamsRequest Request;
typedef SetForceControlParamsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetForceControlParams
} // namespace kinova_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::kinova_msgs::SetForceControlParams > {
  static const char* value()
  {
    return "5c0999be3d1c60dba47ea0b2fd08231e";
  }

  static const char* value(const ::kinova_msgs::SetForceControlParams&) { return value(); }
};

template<>
struct DataType< ::kinova_msgs::SetForceControlParams > {
  static const char* value()
  {
    return "kinova_msgs/SetForceControlParams";
  }

  static const char* value(const ::kinova_msgs::SetForceControlParams&) { return value(); }
};


// service_traits::MD5Sum< ::kinova_msgs::SetForceControlParamsRequest> should match 
// service_traits::MD5Sum< ::kinova_msgs::SetForceControlParams > 
template<>
struct MD5Sum< ::kinova_msgs::SetForceControlParamsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::kinova_msgs::SetForceControlParams >::value();
  }
  static const char* value(const ::kinova_msgs::SetForceControlParamsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::kinova_msgs::SetForceControlParamsRequest> should match 
// service_traits::DataType< ::kinova_msgs::SetForceControlParams > 
template<>
struct DataType< ::kinova_msgs::SetForceControlParamsRequest>
{
  static const char* value()
  {
    return DataType< ::kinova_msgs::SetForceControlParams >::value();
  }
  static const char* value(const ::kinova_msgs::SetForceControlParamsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::kinova_msgs::SetForceControlParamsResponse> should match 
// service_traits::MD5Sum< ::kinova_msgs::SetForceControlParams > 
template<>
struct MD5Sum< ::kinova_msgs::SetForceControlParamsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::kinova_msgs::SetForceControlParams >::value();
  }
  static const char* value(const ::kinova_msgs::SetForceControlParamsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::kinova_msgs::SetForceControlParamsResponse> should match 
// service_traits::DataType< ::kinova_msgs::SetForceControlParams > 
template<>
struct DataType< ::kinova_msgs::SetForceControlParamsResponse>
{
  static const char* value()
  {
    return DataType< ::kinova_msgs::SetForceControlParams >::value();
  }
  static const char* value(const ::kinova_msgs::SetForceControlParamsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KINOVA_MSGS_MESSAGE_SETFORCECONTROLPARAMS_H
