// Generated by gencpp from file kinova_msgs/SetNullSpaceModeState.msg
// DO NOT EDIT!


#ifndef KINOVA_MSGS_MESSAGE_SETNULLSPACEMODESTATE_H
#define KINOVA_MSGS_MESSAGE_SETNULLSPACEMODESTATE_H

#include <ros/service_traits.h>


#include <kinova_msgs/SetNullSpaceModeStateRequest.h>
#include <kinova_msgs/SetNullSpaceModeStateResponse.h>


namespace kinova_msgs
{

struct SetNullSpaceModeState
{

typedef SetNullSpaceModeStateRequest Request;
typedef SetNullSpaceModeStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetNullSpaceModeState
} // namespace kinova_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::kinova_msgs::SetNullSpaceModeState > {
  static const char* value()
  {
    return "891b541ef99af7889d0f22a062410be8";
  }

  static const char* value(const ::kinova_msgs::SetNullSpaceModeState&) { return value(); }
};

template<>
struct DataType< ::kinova_msgs::SetNullSpaceModeState > {
  static const char* value()
  {
    return "kinova_msgs/SetNullSpaceModeState";
  }

  static const char* value(const ::kinova_msgs::SetNullSpaceModeState&) { return value(); }
};


// service_traits::MD5Sum< ::kinova_msgs::SetNullSpaceModeStateRequest> should match 
// service_traits::MD5Sum< ::kinova_msgs::SetNullSpaceModeState > 
template<>
struct MD5Sum< ::kinova_msgs::SetNullSpaceModeStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::kinova_msgs::SetNullSpaceModeState >::value();
  }
  static const char* value(const ::kinova_msgs::SetNullSpaceModeStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::kinova_msgs::SetNullSpaceModeStateRequest> should match 
// service_traits::DataType< ::kinova_msgs::SetNullSpaceModeState > 
template<>
struct DataType< ::kinova_msgs::SetNullSpaceModeStateRequest>
{
  static const char* value()
  {
    return DataType< ::kinova_msgs::SetNullSpaceModeState >::value();
  }
  static const char* value(const ::kinova_msgs::SetNullSpaceModeStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::kinova_msgs::SetNullSpaceModeStateResponse> should match 
// service_traits::MD5Sum< ::kinova_msgs::SetNullSpaceModeState > 
template<>
struct MD5Sum< ::kinova_msgs::SetNullSpaceModeStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::kinova_msgs::SetNullSpaceModeState >::value();
  }
  static const char* value(const ::kinova_msgs::SetNullSpaceModeStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::kinova_msgs::SetNullSpaceModeStateResponse> should match 
// service_traits::DataType< ::kinova_msgs::SetNullSpaceModeState > 
template<>
struct DataType< ::kinova_msgs::SetNullSpaceModeStateResponse>
{
  static const char* value()
  {
    return DataType< ::kinova_msgs::SetNullSpaceModeState >::value();
  }
  static const char* value(const ::kinova_msgs::SetNullSpaceModeStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KINOVA_MSGS_MESSAGE_SETNULLSPACEMODESTATE_H
