// Generated by gencpp from file kinova_msgs/SetTorqueControlMode.msg
// DO NOT EDIT!


#ifndef KINOVA_MSGS_MESSAGE_SETTORQUECONTROLMODE_H
#define KINOVA_MSGS_MESSAGE_SETTORQUECONTROLMODE_H

#include <ros/service_traits.h>


#include <kinova_msgs/SetTorqueControlModeRequest.h>
#include <kinova_msgs/SetTorqueControlModeResponse.h>


namespace kinova_msgs
{

struct SetTorqueControlMode
{

typedef SetTorqueControlModeRequest Request;
typedef SetTorqueControlModeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetTorqueControlMode
} // namespace kinova_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::kinova_msgs::SetTorqueControlMode > {
  static const char* value()
  {
    return "891b541ef99af7889d0f22a062410be8";
  }

  static const char* value(const ::kinova_msgs::SetTorqueControlMode&) { return value(); }
};

template<>
struct DataType< ::kinova_msgs::SetTorqueControlMode > {
  static const char* value()
  {
    return "kinova_msgs/SetTorqueControlMode";
  }

  static const char* value(const ::kinova_msgs::SetTorqueControlMode&) { return value(); }
};


// service_traits::MD5Sum< ::kinova_msgs::SetTorqueControlModeRequest> should match 
// service_traits::MD5Sum< ::kinova_msgs::SetTorqueControlMode > 
template<>
struct MD5Sum< ::kinova_msgs::SetTorqueControlModeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::kinova_msgs::SetTorqueControlMode >::value();
  }
  static const char* value(const ::kinova_msgs::SetTorqueControlModeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::kinova_msgs::SetTorqueControlModeRequest> should match 
// service_traits::DataType< ::kinova_msgs::SetTorqueControlMode > 
template<>
struct DataType< ::kinova_msgs::SetTorqueControlModeRequest>
{
  static const char* value()
  {
    return DataType< ::kinova_msgs::SetTorqueControlMode >::value();
  }
  static const char* value(const ::kinova_msgs::SetTorqueControlModeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::kinova_msgs::SetTorqueControlModeResponse> should match 
// service_traits::MD5Sum< ::kinova_msgs::SetTorqueControlMode > 
template<>
struct MD5Sum< ::kinova_msgs::SetTorqueControlModeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::kinova_msgs::SetTorqueControlMode >::value();
  }
  static const char* value(const ::kinova_msgs::SetTorqueControlModeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::kinova_msgs::SetTorqueControlModeResponse> should match 
// service_traits::DataType< ::kinova_msgs::SetTorqueControlMode > 
template<>
struct DataType< ::kinova_msgs::SetTorqueControlModeResponse>
{
  static const char* value()
  {
    return DataType< ::kinova_msgs::SetTorqueControlMode >::value();
  }
  static const char* value(const ::kinova_msgs::SetTorqueControlModeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KINOVA_MSGS_MESSAGE_SETTORQUECONTROLMODE_H
