// Generated by gencpp from file kinova_msgs/SetTorqueControlParameters.msg
// DO NOT EDIT!


#ifndef KINOVA_MSGS_MESSAGE_SETTORQUECONTROLPARAMETERS_H
#define KINOVA_MSGS_MESSAGE_SETTORQUECONTROLPARAMETERS_H

#include <ros/service_traits.h>


#include <kinova_msgs/SetTorqueControlParametersRequest.h>
#include <kinova_msgs/SetTorqueControlParametersResponse.h>


namespace kinova_msgs
{

struct SetTorqueControlParameters
{

typedef SetTorqueControlParametersRequest Request;
typedef SetTorqueControlParametersResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetTorqueControlParameters
} // namespace kinova_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::kinova_msgs::SetTorqueControlParameters > {
  static const char* value()
  {
    return "c22f2a1ed8654a0b365f1bb3f7ff2c0f";
  }

  static const char* value(const ::kinova_msgs::SetTorqueControlParameters&) { return value(); }
};

template<>
struct DataType< ::kinova_msgs::SetTorqueControlParameters > {
  static const char* value()
  {
    return "kinova_msgs/SetTorqueControlParameters";
  }

  static const char* value(const ::kinova_msgs::SetTorqueControlParameters&) { return value(); }
};


// service_traits::MD5Sum< ::kinova_msgs::SetTorqueControlParametersRequest> should match 
// service_traits::MD5Sum< ::kinova_msgs::SetTorqueControlParameters > 
template<>
struct MD5Sum< ::kinova_msgs::SetTorqueControlParametersRequest>
{
  static const char* value()
  {
    return MD5Sum< ::kinova_msgs::SetTorqueControlParameters >::value();
  }
  static const char* value(const ::kinova_msgs::SetTorqueControlParametersRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::kinova_msgs::SetTorqueControlParametersRequest> should match 
// service_traits::DataType< ::kinova_msgs::SetTorqueControlParameters > 
template<>
struct DataType< ::kinova_msgs::SetTorqueControlParametersRequest>
{
  static const char* value()
  {
    return DataType< ::kinova_msgs::SetTorqueControlParameters >::value();
  }
  static const char* value(const ::kinova_msgs::SetTorqueControlParametersRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::kinova_msgs::SetTorqueControlParametersResponse> should match 
// service_traits::MD5Sum< ::kinova_msgs::SetTorqueControlParameters > 
template<>
struct MD5Sum< ::kinova_msgs::SetTorqueControlParametersResponse>
{
  static const char* value()
  {
    return MD5Sum< ::kinova_msgs::SetTorqueControlParameters >::value();
  }
  static const char* value(const ::kinova_msgs::SetTorqueControlParametersResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::kinova_msgs::SetTorqueControlParametersResponse> should match 
// service_traits::DataType< ::kinova_msgs::SetTorqueControlParameters > 
template<>
struct DataType< ::kinova_msgs::SetTorqueControlParametersResponse>
{
  static const char* value()
  {
    return DataType< ::kinova_msgs::SetTorqueControlParameters >::value();
  }
  static const char* value(const ::kinova_msgs::SetTorqueControlParametersResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KINOVA_MSGS_MESSAGE_SETTORQUECONTROLPARAMETERS_H
