// Generated by gencpp from file kinova_msgs/Start.msg
// DO NOT EDIT!


#ifndef KINOVA_MSGS_MESSAGE_START_H
#define KINOVA_MSGS_MESSAGE_START_H

#include <ros/service_traits.h>


#include <kinova_msgs/StartRequest.h>
#include <kinova_msgs/StartResponse.h>


namespace kinova_msgs
{

struct Start
{

typedef StartRequest Request;
typedef StartResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Start
} // namespace kinova_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::kinova_msgs::Start > {
  static const char* value()
  {
    return "e762e31d813526eaaa6a12e8354174fc";
  }

  static const char* value(const ::kinova_msgs::Start&) { return value(); }
};

template<>
struct DataType< ::kinova_msgs::Start > {
  static const char* value()
  {
    return "kinova_msgs/Start";
  }

  static const char* value(const ::kinova_msgs::Start&) { return value(); }
};


// service_traits::MD5Sum< ::kinova_msgs::StartRequest> should match 
// service_traits::MD5Sum< ::kinova_msgs::Start > 
template<>
struct MD5Sum< ::kinova_msgs::StartRequest>
{
  static const char* value()
  {
    return MD5Sum< ::kinova_msgs::Start >::value();
  }
  static const char* value(const ::kinova_msgs::StartRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::kinova_msgs::StartRequest> should match 
// service_traits::DataType< ::kinova_msgs::Start > 
template<>
struct DataType< ::kinova_msgs::StartRequest>
{
  static const char* value()
  {
    return DataType< ::kinova_msgs::Start >::value();
  }
  static const char* value(const ::kinova_msgs::StartRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::kinova_msgs::StartResponse> should match 
// service_traits::MD5Sum< ::kinova_msgs::Start > 
template<>
struct MD5Sum< ::kinova_msgs::StartResponse>
{
  static const char* value()
  {
    return MD5Sum< ::kinova_msgs::Start >::value();
  }
  static const char* value(const ::kinova_msgs::StartResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::kinova_msgs::StartResponse> should match 
// service_traits::DataType< ::kinova_msgs::Start > 
template<>
struct DataType< ::kinova_msgs::StartResponse>
{
  static const char* value()
  {
    return DataType< ::kinova_msgs::Start >::value();
  }
  static const char* value(const ::kinova_msgs::StartResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KINOVA_MSGS_MESSAGE_START_H
