// Generated by gencpp from file kinova_msgs/ZeroTorques.msg
// DO NOT EDIT!


#ifndef KINOVA_MSGS_MESSAGE_ZEROTORQUES_H
#define KINOVA_MSGS_MESSAGE_ZEROTORQUES_H

#include <ros/service_traits.h>


#include <kinova_msgs/ZeroTorquesRequest.h>
#include <kinova_msgs/ZeroTorquesResponse.h>


namespace kinova_msgs
{

struct ZeroTorques
{

typedef ZeroTorquesRequest Request;
typedef ZeroTorquesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ZeroTorques
} // namespace kinova_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::kinova_msgs::ZeroTorques > {
  static const char* value()
  {
    return "c22f2a1ed8654a0b365f1bb3f7ff2c0f";
  }

  static const char* value(const ::kinova_msgs::ZeroTorques&) { return value(); }
};

template<>
struct DataType< ::kinova_msgs::ZeroTorques > {
  static const char* value()
  {
    return "kinova_msgs/ZeroTorques";
  }

  static const char* value(const ::kinova_msgs::ZeroTorques&) { return value(); }
};


// service_traits::MD5Sum< ::kinova_msgs::ZeroTorquesRequest> should match 
// service_traits::MD5Sum< ::kinova_msgs::ZeroTorques > 
template<>
struct MD5Sum< ::kinova_msgs::ZeroTorquesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::kinova_msgs::ZeroTorques >::value();
  }
  static const char* value(const ::kinova_msgs::ZeroTorquesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::kinova_msgs::ZeroTorquesRequest> should match 
// service_traits::DataType< ::kinova_msgs::ZeroTorques > 
template<>
struct DataType< ::kinova_msgs::ZeroTorquesRequest>
{
  static const char* value()
  {
    return DataType< ::kinova_msgs::ZeroTorques >::value();
  }
  static const char* value(const ::kinova_msgs::ZeroTorquesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::kinova_msgs::ZeroTorquesResponse> should match 
// service_traits::MD5Sum< ::kinova_msgs::ZeroTorques > 
template<>
struct MD5Sum< ::kinova_msgs::ZeroTorquesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::kinova_msgs::ZeroTorques >::value();
  }
  static const char* value(const ::kinova_msgs::ZeroTorquesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::kinova_msgs::ZeroTorquesResponse> should match 
// service_traits::DataType< ::kinova_msgs::ZeroTorques > 
template<>
struct DataType< ::kinova_msgs::ZeroTorquesResponse>
{
  static const char* value()
  {
    return DataType< ::kinova_msgs::ZeroTorques >::value();
  }
  static const char* value(const ::kinova_msgs::ZeroTorquesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KINOVA_MSGS_MESSAGE_ZEROTORQUES_H
