; Auto-generated. Do not edit!


(cl:in-package kinova_msgs-msg)


;//! \htmlinclude Arm_KinovaPoseGoal.msg.html

(cl:defclass <Arm_KinovaPoseGoal> (roslisp-msg-protocol:ros-message)
  ((kinova_pose
    :reader kinova_pose
    :initarg :kinova_pose
    :type kinova_msgs-msg:KinovaPose
    :initform (cl:make-instance 'kinova_msgs-msg:KinovaPose)))
)

(cl:defclass Arm_KinovaPoseGoal (<Arm_KinovaPoseGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <Arm_KinovaPoseGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'Arm_KinovaPoseGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name kinova_msgs-msg:<Arm_KinovaPoseGoal> is deprecated: use kinova_msgs-msg:Arm_KinovaPoseGoal instead.")))

(cl:ensure-generic-function 'kinova_pose-val :lambda-list '(m))
(cl:defmethod kinova_pose-val ((m <Arm_KinovaPoseGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader kinova_msgs-msg:kinova_pose-val is deprecated.  Use kinova_msgs-msg:kinova_pose instead.")
  (kinova_pose m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <Arm_KinovaPoseGoal>) ostream)
  "Serializes a message object of type '<Arm_KinovaPoseGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'kinova_pose) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <Arm_KinovaPoseGoal>) istream)
  "Deserializes a message object of type '<Arm_KinovaPoseGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'kinova_pose) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<Arm_KinovaPoseGoal>)))
  "Returns string type for a message object of type '<Arm_KinovaPoseGoal>"
  "kinova_msgs/Arm_KinovaPoseGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'Arm_KinovaPoseGoal)))
  "Returns string type for a message object of type 'Arm_KinovaPoseGoal"
  "kinova_msgs/Arm_KinovaPoseGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<Arm_KinovaPoseGoal>)))
  "Returns md5sum for a message object of type '<Arm_KinovaPoseGoal>"
  "a3d0acc7643d70196e513c76ce4fd6d9")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'Arm_KinovaPoseGoal)))
  "Returns md5sum for a message object of type 'Arm_KinovaPoseGoal"
  "a3d0acc7643d70196e513c76ce4fd6d9")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<Arm_KinovaPoseGoal>)))
  "Returns full string definition for message of type '<Arm_KinovaPoseGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal~%KinovaPose kinova_pose~%~%================================================================================~%MSG: kinova_msgs/KinovaPose~%float32 X~%float32 Y~%float32 Z~%float32 ThetaX~%float32 ThetaY~%float32 ThetaZ~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'Arm_KinovaPoseGoal)))
  "Returns full string definition for message of type 'Arm_KinovaPoseGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal~%KinovaPose kinova_pose~%~%================================================================================~%MSG: kinova_msgs/KinovaPose~%float32 X~%float32 Y~%float32 Z~%float32 ThetaX~%float32 ThetaY~%float32 ThetaZ~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <Arm_KinovaPoseGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'kinova_pose))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <Arm_KinovaPoseGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'Arm_KinovaPoseGoal
    (cl:cons ':kinova_pose (kinova_pose msg))
))
