; Auto-generated. Do not edit!


(cl:in-package kinova_msgs-msg)


;//! \htmlinclude Arm_KinovaPoseFeedback.msg.html

(cl:defclass <Arm_KinovaPoseFeedback> (roslisp-msg-protocol:ros-message)
  ((kinova_pose
    :reader kinova_pose
    :initarg :kinova_pose
    :type kinova_msgs-msg:KinovaPose
    :initform (cl:make-instance 'kinova_msgs-msg:KinovaPose)))
)

(cl:defclass Arm_KinovaPoseFeedback (<Arm_KinovaPoseFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <Arm_KinovaPoseFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'Arm_KinovaPoseFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name kinova_msgs-msg:<Arm_KinovaPoseFeedback> is deprecated: use kinova_msgs-msg:Arm_KinovaPoseFeedback instead.")))

(cl:ensure-generic-function 'kinova_pose-val :lambda-list '(m))
(cl:defmethod kinova_pose-val ((m <Arm_KinovaPoseFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader kinova_msgs-msg:kinova_pose-val is deprecated.  Use kinova_msgs-msg:kinova_pose instead.")
  (kinova_pose m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <Arm_KinovaPoseFeedback>) ostream)
  "Serializes a message object of type '<Arm_KinovaPoseFeedback>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'kinova_pose) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <Arm_KinovaPoseFeedback>) istream)
  "Deserializes a message object of type '<Arm_KinovaPoseFeedback>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'kinova_pose) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<Arm_KinovaPoseFeedback>)))
  "Returns string type for a message object of type '<Arm_KinovaPoseFeedback>"
  "kinova_msgs/Arm_KinovaPoseFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'Arm_KinovaPoseFeedback)))
  "Returns string type for a message object of type 'Arm_KinovaPoseFeedback"
  "kinova_msgs/Arm_KinovaPoseFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<Arm_KinovaPoseFeedback>)))
  "Returns md5sum for a message object of type '<Arm_KinovaPoseFeedback>"
  "a3d0acc7643d70196e513c76ce4fd6d9")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'Arm_KinovaPoseFeedback)))
  "Returns md5sum for a message object of type 'Arm_KinovaPoseFeedback"
  "a3d0acc7643d70196e513c76ce4fd6d9")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<Arm_KinovaPoseFeedback>)))
  "Returns full string definition for message of type '<Arm_KinovaPoseFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Feedback message~%KinovaPose kinova_pose~%~%================================================================================~%MSG: kinova_msgs/KinovaPose~%float32 X~%float32 Y~%float32 Z~%float32 ThetaX~%float32 ThetaY~%float32 ThetaZ~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'Arm_KinovaPoseFeedback)))
  "Returns full string definition for message of type 'Arm_KinovaPoseFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Feedback message~%KinovaPose kinova_pose~%~%================================================================================~%MSG: kinova_msgs/KinovaPose~%float32 X~%float32 Y~%float32 Z~%float32 ThetaX~%float32 ThetaY~%float32 ThetaZ~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <Arm_KinovaPoseFeedback>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'kinova_pose))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <Arm_KinovaPoseFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'Arm_KinovaPoseFeedback
    (cl:cons ':kinova_pose (kinova_pose msg))
))
