; Auto-generated. Do not edit!


(cl:in-package kinova_msgs-msg)


;//! \htmlinclude ArmJointAnglesFeedback.msg.html

(cl:defclass <ArmJointAnglesFeedback> (roslisp-msg-protocol:ros-message)
  ((angles
    :reader angles
    :initarg :angles
    :type kinova_msgs-msg:JointAngles
    :initform (cl:make-instance 'kinova_msgs-msg:JointAngles)))
)

(cl:defclass ArmJointAnglesFeedback (<ArmJointAnglesFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ArmJointAnglesFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ArmJointAnglesFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name kinova_msgs-msg:<ArmJointAnglesFeedback> is deprecated: use kinova_msgs-msg:ArmJointAnglesFeedback instead.")))

(cl:ensure-generic-function 'angles-val :lambda-list '(m))
(cl:defmethod angles-val ((m <ArmJointAnglesFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader kinova_msgs-msg:angles-val is deprecated.  Use kinova_msgs-msg:angles instead.")
  (angles m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ArmJointAnglesFeedback>) ostream)
  "Serializes a message object of type '<ArmJointAnglesFeedback>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'angles) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ArmJointAnglesFeedback>) istream)
  "Deserializes a message object of type '<ArmJointAnglesFeedback>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'angles) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ArmJointAnglesFeedback>)))
  "Returns string type for a message object of type '<ArmJointAnglesFeedback>"
  "kinova_msgs/ArmJointAnglesFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ArmJointAnglesFeedback)))
  "Returns string type for a message object of type 'ArmJointAnglesFeedback"
  "kinova_msgs/ArmJointAnglesFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ArmJointAnglesFeedback>)))
  "Returns md5sum for a message object of type '<ArmJointAnglesFeedback>"
  "cadc8c9df1338a45563e10d707e71551")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ArmJointAnglesFeedback)))
  "Returns md5sum for a message object of type 'ArmJointAnglesFeedback"
  "cadc8c9df1338a45563e10d707e71551")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ArmJointAnglesFeedback>)))
  "Returns full string definition for message of type '<ArmJointAnglesFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Feedback~%JointAngles angles~%~%~%================================================================================~%MSG: kinova_msgs/JointAngles~%float32 joint1~%float32 joint2~%float32 joint3~%float32 joint4~%float32 joint5~%float32 joint6~%float32 joint7~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ArmJointAnglesFeedback)))
  "Returns full string definition for message of type 'ArmJointAnglesFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Feedback~%JointAngles angles~%~%~%================================================================================~%MSG: kinova_msgs/JointAngles~%float32 joint1~%float32 joint2~%float32 joint3~%float32 joint4~%float32 joint5~%float32 joint6~%float32 joint7~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ArmJointAnglesFeedback>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'angles))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ArmJointAnglesFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'ArmJointAnglesFeedback
    (cl:cons ':angles (angles msg))
))
