; Auto-generated. Do not edit!


(cl:in-package kinova_msgs-msg)


;//! \htmlinclude SetFingersPositionResult.msg.html

(cl:defclass <SetFingersPositionResult> (roslisp-msg-protocol:ros-message)
  ((fingers
    :reader fingers
    :initarg :fingers
    :type kinova_msgs-msg:FingerPosition
    :initform (cl:make-instance 'kinova_msgs-msg:FingerPosition)))
)

(cl:defclass SetFingersPositionResult (<SetFingersPositionResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <SetFingersPositionResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'SetFingersPositionResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name kinova_msgs-msg:<SetFingersPositionResult> is deprecated: use kinova_msgs-msg:SetFingersPositionResult instead.")))

(cl:ensure-generic-function 'fingers-val :lambda-list '(m))
(cl:defmethod fingers-val ((m <SetFingersPositionResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader kinova_msgs-msg:fingers-val is deprecated.  Use kinova_msgs-msg:fingers instead.")
  (fingers m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <SetFingersPositionResult>) ostream)
  "Serializes a message object of type '<SetFingersPositionResult>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'fingers) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <SetFingersPositionResult>) istream)
  "Deserializes a message object of type '<SetFingersPositionResult>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'fingers) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<SetFingersPositionResult>)))
  "Returns string type for a message object of type '<SetFingersPositionResult>"
  "kinova_msgs/SetFingersPositionResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'SetFingersPositionResult)))
  "Returns string type for a message object of type 'SetFingersPositionResult"
  "kinova_msgs/SetFingersPositionResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<SetFingersPositionResult>)))
  "Returns md5sum for a message object of type '<SetFingersPositionResult>"
  "bdbf88b45be6ef8cd65f0b4fc487d49d")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'SetFingersPositionResult)))
  "Returns md5sum for a message object of type 'SetFingersPositionResult"
  "bdbf88b45be6ef8cd65f0b4fc487d49d")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<SetFingersPositionResult>)))
  "Returns full string definition for message of type '<SetFingersPositionResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result~%FingerPosition fingers~%~%================================================================================~%MSG: kinova_msgs/FingerPosition~%float32 finger1~%float32 finger2~%float32 finger3~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'SetFingersPositionResult)))
  "Returns full string definition for message of type 'SetFingersPositionResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result~%FingerPosition fingers~%~%================================================================================~%MSG: kinova_msgs/FingerPosition~%float32 finger1~%float32 finger2~%float32 finger3~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <SetFingersPositionResult>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'fingers))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <SetFingersPositionResult>))
  "Converts a ROS message object to a list"
  (cl:list 'SetFingersPositionResult
    (cl:cons ':fingers (fingers msg))
))
