; Auto-generated. Do not edit!


(cl:in-package kinova_msgs-msg)


;//! \htmlinclude SetFingersPositionFeedback.msg.html

(cl:defclass <SetFingersPositionFeedback> (roslisp-msg-protocol:ros-message)
  ((fingers
    :reader fingers
    :initarg :fingers
    :type kinova_msgs-msg:FingerPosition
    :initform (cl:make-instance 'kinova_msgs-msg:FingerPosition)))
)

(cl:defclass SetFingersPositionFeedback (<SetFingersPositionFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <SetFingersPositionFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'SetFingersPositionFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name kinova_msgs-msg:<SetFingersPositionFeedback> is deprecated: use kinova_msgs-msg:SetFingersPositionFeedback instead.")))

(cl:ensure-generic-function 'fingers-val :lambda-list '(m))
(cl:defmethod fingers-val ((m <SetFingersPositionFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader kinova_msgs-msg:fingers-val is deprecated.  Use kinova_msgs-msg:fingers instead.")
  (fingers m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <SetFingersPositionFeedback>) ostream)
  "Serializes a message object of type '<SetFingersPositionFeedback>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'fingers) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <SetFingersPositionFeedback>) istream)
  "Deserializes a message object of type '<SetFingersPositionFeedback>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'fingers) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<SetFingersPositionFeedback>)))
  "Returns string type for a message object of type '<SetFingersPositionFeedback>"
  "kinova_msgs/SetFingersPositionFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'SetFingersPositionFeedback)))
  "Returns string type for a message object of type 'SetFingersPositionFeedback"
  "kinova_msgs/SetFingersPositionFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<SetFingersPositionFeedback>)))
  "Returns md5sum for a message object of type '<SetFingersPositionFeedback>"
  "bdbf88b45be6ef8cd65f0b4fc487d49d")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'SetFingersPositionFeedback)))
  "Returns md5sum for a message object of type 'SetFingersPositionFeedback"
  "bdbf88b45be6ef8cd65f0b4fc487d49d")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<SetFingersPositionFeedback>)))
  "Returns full string definition for message of type '<SetFingersPositionFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Feedback message~%FingerPosition fingers~%~%~%================================================================================~%MSG: kinova_msgs/FingerPosition~%float32 finger1~%float32 finger2~%float32 finger3~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'SetFingersPositionFeedback)))
  "Returns full string definition for message of type 'SetFingersPositionFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Feedback message~%FingerPosition fingers~%~%~%================================================================================~%MSG: kinova_msgs/FingerPosition~%float32 finger1~%float32 finger2~%float32 finger3~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <SetFingersPositionFeedback>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'fingers))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <SetFingersPositionFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'SetFingersPositionFeedback
    (cl:cons ':fingers (fingers msg))
))
