// Generated by gencpp from file pingpong/Kinematics.msg
// DO NOT EDIT!


#ifndef PINGPONG_MESSAGE_KINEMATICS_H
#define PINGPONG_MESSAGE_KINEMATICS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>

namespace pingpong
{
template <class ContainerAllocator>
struct Kinematics_
{
  typedef Kinematics_<ContainerAllocator> Type;

  Kinematics_()
    : position()
    , velocity()
    , acceleration()
    , controlled(false)  {
    }
  Kinematics_(const ContainerAllocator& _alloc)
    : position(_alloc)
    , velocity(_alloc)
    , acceleration(_alloc)
    , controlled(false)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _velocity_type;
  _velocity_type velocity;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _acceleration_type;
  _acceleration_type acceleration;

   typedef uint8_t _controlled_type;
  _controlled_type controlled;




  typedef boost::shared_ptr< ::pingpong::Kinematics_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pingpong::Kinematics_<ContainerAllocator> const> ConstPtr;

}; // struct Kinematics_

typedef ::pingpong::Kinematics_<std::allocator<void> > Kinematics;

typedef boost::shared_ptr< ::pingpong::Kinematics > KinematicsPtr;
typedef boost::shared_ptr< ::pingpong::Kinematics const> KinematicsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pingpong::Kinematics_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pingpong::Kinematics_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pingpong

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'pingpong': ['/home/pepe/melendez_ws/src/pingpong/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pingpong::Kinematics_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pingpong::Kinematics_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pingpong::Kinematics_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pingpong::Kinematics_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pingpong::Kinematics_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pingpong::Kinematics_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pingpong::Kinematics_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2f605c13c499160cdf7517a158ac14b7";
  }

  static const char* value(const ::pingpong::Kinematics_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2f605c13c499160cULL;
  static const uint64_t static_value2 = 0xdf7517a158ac14b7ULL;
};

template<class ContainerAllocator>
struct DataType< ::pingpong::Kinematics_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pingpong/Kinematics";
  }

  static const char* value(const ::pingpong::Kinematics_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pingpong::Kinematics_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Vector3 position\n\
geometry_msgs/Vector3 velocity\n\
geometry_msgs/Vector3 acceleration\n\
bool controlled\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::pingpong::Kinematics_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pingpong::Kinematics_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position);
      stream.next(m.velocity);
      stream.next(m.acceleration);
      stream.next(m.controlled);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Kinematics_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pingpong::Kinematics_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pingpong::Kinematics_<ContainerAllocator>& v)
  {
    s << indent << "position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    s << indent << "velocity: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.velocity);
    s << indent << "acceleration: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.acceleration);
    s << indent << "controlled: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.controlled);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PINGPONG_MESSAGE_KINEMATICS_H
